### PR TITLE
feat(json-parse): allow JSON.parse() to be generic

### PR DESCRIPTION
**Pull request by DanielKucal**
Sometimes we know what kind of data we're working on, in such case we should be able to do `const car = JSON.parse<Car>(carJson)`

### CODE REVIEW

**Comment by DanielKucal** [comment]
Okay, I've seen at the end of README that you don't want to include this, closing then.

**Comment by pranavjindal999** [comment]
TBH, I do not agree with what they say in the readme. 
When I know what the type is, I should be able to tell TS my `type` confidently.

using `as myType` looks hackish.

**Comment by pranavjindal999** [comment]
@mattpocock If there are so many PRs coming up for this fix, it ideally means that using the generic parse is more natural than using `as`.

**Comment by mattpocock** [comment]
Please refer to the readme for my thoughts. It's not about ergonomics, but correctness.

**Pull request closed without merging**
