### PR TITLE
Add monorepo instructions to the README

### PR DESCRIPTION
**Pull request by RhysSullivan**
Just setup ts-reset for my monorepo and found this was the most painless way to do it, updated the README to reflect how I set this up for my monorepo, this allows you to only install it once into the root package json

### CODE REVIEW

**Comment by feedm3** [comment]
Thanks for this solution, I just tested it and it works :)

One question though: Why is it necessary to have the `reset.d.ts` file inside the root? I try to avoid adding files to the package root in general to keep it more tidy. When adding a `reset.d.ts` file inside the package, typescript doesn't care for it. Even if I include it explicitly like with the package root file and I have a hard time to understand it.

**Comment by the-ult** [comment]
Somehow can't get it to work with [Nx devtools](https:/nx.dev)

Tried al the above (and more)
Only solution working for now is adding:
`import '@total-typescript/ts-reset';` to my `apps/my-app/src/main.ts` file (when using Angular)

**Comment by MendyLanda** [comment]
> **Edit 1** Here is a nice thread about the different ways of importing it: #30
> 
> After trying out more things I actually ended up including the `reset.d.ts` file in the package root `tsconfig.json` with `"files": ["./reset.d.ts"]`. With this I have the types in all our packages, cause each package has it's own `tsconfig.json` which extends from this package root `tsconfig.json`.

This did work for me across all apps and packages. 
In my root tsconfig: `"files": ["./reset.d.ts"]`

**Comment by nkeil** [comment]
After playing around with some different solutions for the monorepo implementation, I also found this to be the cleanest way to make it work.

**Comment by FleetAdmiralJakob** [comment]
Needed an instruction and this one worked

**Comment by mattpocock** [comment]
I'm not sure about this one. It seems like the ideal solution would:

1. Be **portable**. Wherever you move the packages/apps, it should not require any changes from the dev to keep `ts-reset` working.
2. Not rely on **implicit dependencies**. With your method, it's unclear which app/package relies on the installation of `ts-reset` in the root of the app. This means it'll hang around like a bad smell even if all your packages migrate away from it.

I think what we should recommend is that each package/app should have a `globals.ts` file which imports `ts-reset`. In other words, exactly the same as when the package is _not_ in a monorepo.

```txt
apps/my-app/globals.ts // ts-reset in here
packages/my-package/globals.ts // ts-reset in here
```

This makes each package portable, and the dependencies are clear.

**Comment by limegorilla** [comment]
Sorry to resurrect.

Something that worked for me was having a dedicated `@acme/tsconfig` tooling package, which I extend every project's `tsconfig` from one main `base.json` file. This keeps everything portable as well - if you pull a project/app out of your monorepo it's implicit that you have to maintain access to dependencies.

So:
```zsh
@acme/tsconfig:
    reset.d.ts  # (Add the type def file here)
    base.json # Add "files": "reset.d.ts" here

@acme/<some project/app etc>:
    tsconfig.json # extends base
```

**Comment by mattpocock** [comment]
@limegorilla I don't think that tsconfigs inherit `files`, just `compilerOptions`. So there is likely something in your setup other than `files` that's causing your success.

**Pull request closed without merging**
