### PR TITLE
Fix for issue 41 - change Map to unknown

### PR DESCRIPTION
**Pull request by pnowak**
I'm not sure if this idea - https://github.com/total-typescript/ts-reset/issues/41- is taken into account, so I didn't complete the readme file.

I could update the readme if this feature will be accepted.

### CODE REVIEW

**Comment by mattpocock** [comment]
This feature makes sense, and I like it! Please add a readme, and some more tests to ensure that the current behaviour of Map is unaffected.

**Comment by pnowak** [comment]
I added only more tests for now but in the last one, TS marked `map.clear()` with squiggly red lines.
Screenshot 2023-02-22 at 17 03 33

I'm not sure why.

**Comment by mattpocock** [comment]
Could you pull in `main`? I've fixed the CI so it should run on your branch now.

**Comment by pnowak** [comment]
I did what you asked for. 

Unfortunately without the expected result. I still have a TS underlined map.clear().

**Comment by mattpocock** [comment]
@pnowak Apologies for the length of time to merge this PR. Great contribution, thanks so much.

**Pull request merged**
